- playground/Readme.md
> BLOCKS-006 added Readme.md to explain load on Chrome [HA]

- Catrobat2Blockly/src/Catrobat2Blockly.java
- Catrobat2Blockly/src/tools/Block.java
- Catrobat2Blockly/src/tools/Parser.java
Finished writing data in blocks
> Blocks 015

- Catrobat2Blockly/src/Catrobat2Blockly.java
- Catrobat2Blockly/src/tools/Block.java
- Catrobat2Blockly/src/tools/Formula.java
- Catrobat2Blockly/src/tools/Parser.java
- Catrobat2Blockly/src/tools/Script.java
> Blocks 017

- BlockLibrary/IfElseLogicBeginBrick.xml
- BlockLibrary/IfLogicBeginBrick.xml
- BlockLibrary/IfThenLogicBeginBrick.xml
- Catrobat2Blockly/src/Catrobat2Blockly.java
- Catrobat2Blockly/src/tools/Block.java
- Catrobat2Blockly/src/tools/Parser.java
- scratch-blocks-develop/blocks_vertical/control.js
> BLOCKS-022 Adapt Blocks and resolve condition issue [WC]

- Catrobat2Blockly/src/Catrobat2Blockly.java
- Catrobat2Blockly/src/tools/Block.java
- Catrobat2Blockly/src/tools/CatFile.java
- Catrobat2Blockly/src/tools/Look.java
- Catrobat2Blockly/src/tools/Object.java
- Catrobat2Blockly/src/tools/Parser.java
- Catrobat2Blockly/src/tools/Scene.java
- Catrobat2Blockly/src/tools/Script.java
Added Relative links to objects and parsing of files & looks & general dropdown support
> Blocks 016

- Catrobat2BlocklyJavaScript/code.xml
- Catrobat2BlocklyJavaScript/src/Catrobat2Blockly.js
- Catrobat2BlocklyJavaScript/src/index.html
- Catrobat2BlocklyJavaScript/src/tools/Parser.js
@juliangoeschl interpretation of Java Parser
> Blocks 031

- Catrobat2BlocklyJavaScript/src/tools/Parser.js
Parser that evaluates formulas
> Blocks 033 -  Formula Parser

- Catrobat2BlocklyJavaScript/src/tools/Parser.js
Dropdowns now have correct name in Maps
> BLOCKS-034 Add support for DD & reformat code (excluding spinners) [CW]

- scratch-blocks-develop/package.json
> added npm run clean [MF]

- src/js/render/file_dropper.js
- src/js/share/share.js
- test/jsunit/share/share.test.js
Fixed bug with wrong height and width by rendering scripts.
> BLOCKS-73 fixed bug with wrong height and width [AK]

- .eslintrc
- docker/po-review/README.md
- test/jest-puppeteer.config.js
- test/jsunit/block/block.test.js
- test/jsunit/msg/msg.test.js
- test/jsunit/parser/parser.test.js
- test/jsunit/share/share.test.js
- test/jsunit/share/share.utils.test.js
- test/jsunit/xml/xml.test.js
Fixed a typo and removed wrong description (according to Andreas).
Added some eslint rules, so jest will be linted right.
> BLOCKS-MAINTENANCE remove wrong description and add globals ignore for jest tests [MF]

- .github/workflows/merge_actions.yaml
- .github/workflows/pull_request_actions.yml
https://jira.catrob.at/browse/BLOCKS-114
Add a GH-Action which triggeres the Test Action of every open PR. 
For testing purposes a [personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) with public_repo rights is required. Set it in your repository settings with the name PRA.
> BLOCKS-114 Rebuild & Rerun Tests on changes after PR

- .github/workflows/pull_request_actions.yml
Add missing event trigger for BLOCKS-114
> BLOCKS-MAINTENANCE add missing event trigger for PR [MF]

- src/js/share/share.js
- src/js/share/utils.js
- test/jsunit/share/share.test.js
https://jira.catrob.at/browse/BLOCKS-105
Fixed collapsed state bug.
Implemented click event handling with jquery and added one test.
> BLOCKS-105 Collapsed State Bug

- src/js/playground/playground.js
- src/js/share/share.js
- src/js/share/utils.js
- test/jsunit/block/block.test.js
Zebra feature was broken, because of the change to Blockly
it is now fixed and colours get changed between their first color and their third, which differentiate not too much.
> Blocks 68-Zebra feature broken

- .github/workflows/merge_actions.yaml
Wait 5 seconds before removing the Label from PR to avoid coincidence.
> BLOCKS-MAINTENANCE wait before remove label [MF]

- src/js/share/share.js
Just a small design fix.
https://jira.catrob.at/browse/BLOCKS-121
> BLOCKS-121 share design fix

- i18n/create_msg.js
- release.config.js
- src/html/release.html
- src/js/catblocks_msgs.js
- src/js/release.js
- src/js/share/share.js
- src/js/share/utils.js
https://jira.catrob.at/browse/BLOCKS-122
Fixed Bugs with paths for i18n and Block icons.
> BLOCKS-122 Media and i18n Links don't work

- src/js/render/render.js
https://jira.catrob.at/browse/BLOCKS-128
If a list of files exist, check if the list is not empty
> BLOCKS-128 PO-Review Docker does not work without passing program

- package.json
- src/html/playground.html
- src/html/release.html
- src/html/render.html
- src/html/share.html
- test/jsunit/msg/msg.test.js
Fixed prettier execution for linux and executed prettier.
> BLOCKS-MAINTAINANCE Linux prettier fix + execute prettier

- brick-support-checker-action/require/checker.py
https://jira.catrob.at/browse/BLOCKS-126
updated checker.py script. Now it checks the import statements in [CategoryBricksFactory](https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/java/org/catrobat/catroid/ui/fragment/CategoryBricksFactory.java) if new bricks were added to Catroid. Also added a map to check some bricks which have a different name in Catblocks.
> BLOCKS-126 refactored ignore list in checker.py

- license
Change license URL in license file.
https://jira.catrob.at/browse/BLOCKS-116
> BLOCKS-116 Update Readme & License URL

- src/library/js/share/share.js
- src/library/js/share/utils.js
- test/jsunit/share/share.test.js
https://jira.catrob.at/browse/BLOCKS-87
Enabled horizontal scrolling. Now all parts of the brick are shown in web view.
> BLOCKS-87 Test horizontal scrolling to show all parts of the bricks in WebView

- src/library/js/share/utils.js
https://jira.catrob.at/browse/BLOCKS-140
improved performance of rendering.
> BLOCKS-140 Rendering JSON objects to DOM is very slow 

- README.md
https://jira.catrob.at/browse/BLOCKS-134
> BLOCKS-134 Create readme

- .gitignore
- .vscode/launch.json
https://jira.catrob.at/browse/BLOCKS-112
> BLOCKS-112: Support Visual Studio Code Breakpoints

- src/intern/js/render/render.js
- src/intern/js/render/utils.js
added now an info message instead of an error message so new developer wont be confused
> BLOCKS-151: added info message instead of error [PL]

- i18n/catroid_strings/values-en/strings.xml
updated default en language file
> BLOCKS-158: updated default en language [PL]

- src/library/js/share/share.js
- src/library/js/share/utils.js
- test/jsunit/share/share.test.js
https://jira.catrob.at/browse/BLOCKS-135
For performance reasons injectNewDom got replaced by generateNewDom in many places. At the end of rendering the Elements are injected to the page.
> BLOCKS-135 Rewrite inject new DOM

- src/common/js/parser/parser.js
- test/jsunit/parser/parser.test.js
updated supportedAppversion and adjusted tests for it
> BLOCKS-160: updated supportedAppVersion

- .github/workflows/merge_actions.yaml
- gh-deploy-new-develop-on-webtest/Dockerfile
- gh-deploy-new-develop-on-webtest/entrypoint.sh
> BLOCKS-166: adjusted github action errors of automatic deploy

- src/library/js/share/share.js
> BLOCKS-94: added ability to pinch to zoom

- github_actions/gh-deploy-new-develop-on-webtest/entrypoint.sh
> BLOCKS-187: resolved the issues with the move and the sum of retvalues

- src/library/html/release.html
- src/library/js/share/share.js
previous behaviour:
Zoom button does nothing if HTML file is not edited
- Krishna Options src does not work 
changed to:
it works now with every html and also without any problems
> Blocks 146: Zoom button should use dynamic created modal HTML

- github_actions/gh-deploy-new-develop-on-webtest/Dockerfile
- github_actions/gh-deploy-new-develop-on-webtest/entrypoint.sh
blocks maintenance for git hub action for automatic deploy to share
> BLOCKS-MAINTENANCE: added tac in the pipe

- github_actions/gh-deploy-new-develop-on-webtest/Dockerfile
> BLOCKS-MAINTENANCE: removed tac package

- github_actions/gh-deploy-new-develop-on-webtest/entrypoint.sh
> BLOCKS-MAINTENANCE: moved git config lines up

- github_actions/gh-deploy-new-develop-on-webtest/entrypoint.sh
> BLOCKS-MAINTENANCE: added echo message

- i18n/catroid_strings/values-en/strings.xml
updated the string.xml "en" language
> BLOCKS-165: updated en language

- i18n/catroid_strings/values-en/strings.xml
- i18n/strings_to_json_mapping.json
- src/library/js/blocks/categories/data.js
> BLOCKS-164: added embroidery brick

- i18n/catroid_strings/values-en/strings.xml
- i18n/strings_to_json_mapping.json
- src/library/js/blocks/categories/sound.js
Added brick
- StartlisteningBrick
> BLOCKS-159: added new brick StartlisteningBrick

- i18n/catroid_strings/values-en/strings.xml
- i18n/strings_to_json_mapping.json
- src/library/js/blocks/categories/assertions.js
Added new assertion brick TapFor
> BLOCKS-157: added TapFor Brick

- .github/workflows/interval_catroid_check_action.yaml
Fix path to interval check github action.
https://jira.catrob.at/browse/BLOCKS-190
> BLOCKS-190 Interval Catroid Check action wrong path

- i18n/strings_to_json_mapping.json
- src/library/js/blocks/categories/control.js
Add ForItemInUserListBrick support.
https://jira.catrob.at/browse/BLOCKS-156
> BLOCKS-156 add ForItemInUserListBrick

- .github/workflows/interval_dependabot_action.yaml
https://jira.catrob.at/browse/BLOCKS-196
Checks every day for a new blockly version and creates a PR
> BLOCKS-196 Create Pull Requests for new npm packages

- src/intern/html/playground.html
- src/intern/html/testing.html
- yarn.lock
fixing all warnings from security tab
https://jira.catrob.at/browse/BLOCKS-102
> BLOCKS-102 Updated Dependencies (security)

- src/library/js/blocks/categories/control.js
Add loop bricks to ForVariableFromToBrick.
https://jira.catrob.at/browse/BLOCKS-193
> BLOCKS-193 Add loop bricks to ForVariableFromToBrick

- src/intern/html/testing.html
- test/jest-puppeteer-debug.config.js
- test/jsunit/share/share.test.js
https://jira.catrob.at/browse/BLOCKS-197
Removed unnecessary Headings, should work for now. Rewrote the test with image popup to work again and use puppeteer how it should be used.
> BLOCKS-197 Testsite in Puppeteer is cropped

- src/library/js/blocks/categories/control.js
- src/library/js/blocks/categories/device.js
- src/library/js/blocks/categories/event.js
- src/library/js/blocks/categories/index.js
- src/library/js/blocks/colours.js
https://jira.catrob.at/browse/BLOCKS-188
> BLOCKS-188 [Maintenance]: add category "device"

- i18n/strings_to_json_mapping.json
- src/library/js/blocks/categories/assertions.js
- src/library/js/blocks/categories/control.js
- src/library/js/blocks/categories/event.js
moved Blocks into new Categorys, added the category device. 
Link: to changes and Testprogramms: https://drive.google.com/drive/folders/1t9Ep889LamnGke58B5vstt8t_b9hs_Zu?usp=sharing
> BLOCKS-163 [CB] moved Blocks into new Category, add category device

- assets/scripts.svg
- src/library/css/share.css
- src/library/js/blocks/categories/control.js
- src/library/js/blocks/categories/device.js
- src/library/js/share/share.js
https://jira.catrob.at/browse/BLOCKS-229
Fix script tab icon.
> BLOCKS-229 Script Icon Bug

- i18n/strings_to_json_mapping.json
- src/library/js/blocks/categories/assertions.js
Fix test of the "finsh tests" brick.
https://jira.catrob.at/browse/BLOCKS-210
> BLOCKS-210 The name of the "Finish tests" brick is wrong

- i18n/catroid_strings/values-en/strings.xml
- i18n/strings_to_json_mapping.json
- src/common/js/parser/parser.js
- src/library/css/share.css
- src/library/js/blocks/bricks.js
- src/library/js/blocks/categories/dummy.js
- src/library/js/blocks/categories/index.js
- src/library/js/blocks/colours.js
- src/library/js/lib.js
- src/library/js/share/share.js
- src/library/js/share/utils.js
- test/jsunit/block/block.test.js
Allows to add bricks to Catblocks in Catroid.
https://jira.catrob.at/browse/BLOCKS-221
> BLOCKS-221 Allow adding bricks

- i18n/catroid_strings/values-en/strings.xml
- i18n/strings_to_json_mapping.json
- src/common/js/parser/parser.js
- src/library/css/share.css
- src/library/js/blocks/bricks.js
- src/library/js/blocks/categories/dummy.js
- src/library/js/blocks/categories/index.js
- src/library/js/blocks/colours.js
- src/library/js/lib.js
- src/library/js/share/share.js
- src/library/js/share/utils.js
- test/jsunit/block/block.test.js
When deleting a brick in Catblocks, this brick is also removed in Catroid.
https://jira.catrob.at/browse/BLOCKS-222
> BLOCKS-222 Allow deleting bricks or brick blocks or scripts

- i18n/catroid_strings/values-en/strings.xml
- i18n/strings_to_json_mapping.json
- src/common/js/parser/parser.js
- src/library/css/share.css
- src/library/js/blocks/bricks.js
- src/library/js/blocks/categories/dummy.js
- src/library/js/blocks/categories/index.js
- src/library/js/blocks/colours.js
- src/library/js/lib.js
- src/library/js/share/share.js
- src/library/js/share/utils.js
- test/jsunit/block/block.test.js
The duplicate option in Catblocks now also duplicates the bricks in Catroid.
https://jira.catrob.at/browse/BLOCKS-224
> BLOCKS-224 Allow copying bricks or brick blocks or scripts ("Duplicate" menu option)

- i18n/catroid_strings/values-en/strings.xml
- i18n/strings_to_json_mapping.json
- src/common/js/parser/parser.js
- src/library/css/share.css
- src/library/js/blocks/bricks.js
- src/library/js/blocks/categories/dummy.js
- src/library/js/blocks/categories/index.js
- src/library/js/blocks/colours.js
- src/library/js/lib.js
- src/library/js/share/share.js
- src/library/js/share/utils.js
- test/jsunit/block/block.test.js
The default "collapse" option in the Blockly workspace is now removed.
https://jira.catrob.at/browse/BLOCKS-226
> BLOCKS-226 Remove Collapse

- src/common/js/parser/parser.js
- src/library/js/blocks/categories/control.js
- src/library/js/blocks/categories/device.js
Fixed all known "unset"-errors https://jira.catrob.at/browse/BLOCKS-234
> BLOCKS-234 Some parameters are rendered as "unset" even though they are simple formulas

- src/intern/js/index.js
- test/jsunit/block/block.test.js
- test/jsunit/msg/msg.test.js
- test/jsunit/parser/parser.test.js
- test/jsunit/performance/performance.test.js
- test/jsunit/share/share.test.js
- test/jsunit/share/share.utils.test.js
- test/jsunit/xml/xml.test.js
https://jira.catrob.at/browse/BLOCKS-201
Rewrite all tests to use puppeteer how it should be and make the tests debuggable.
> BLOCKS-201 Fix Tests to use puppeteer properly

- i18n/catroid_strings/values-en/strings.xml
- i18n/strings_to_json_mapping.json
- src/library/js/blocks/categories/user.js
https://jira.catrob.at/browse/BLOCKS-249
Add ReportBrick and update english.
> BLOCKS-249 Update bricks and languages

- github_actions/catroid-support-checker-action/Dockerfile
- github_actions/catroid-support-checker-action/entrypoint.sh
- github_actions/catroid-support-checker-action/require/checker.py
https://jira.catrob.at/browse/BLOCKS-225
The GH action was modifed in a way that the category of Catroid and Catblocks bricks is also compared and reported.
> BLOCKS-225 Check Change in brick colors

- github_actions/gh-pages-deploy-action/Dockerfile
- github_actions/gh-pages-deploy-action/entrypoint.sh
- github_actions/gh-pages-deploy-action/require/PREvaluator.py
https://jira.catrob.at/browse/BLOCKS-239
Add the PR number to the deploy commit message.
> BLOCKS-239 Change GH Pages deploy commit message to feature PR number

- src/library/js/integration/catroid.js
https://jira.catrob.at/browse/BLOCKS-242
The bricks are now added with the correct values from Catroid.
> BLOCKS-242 Improve adding bricks in Catroid

- package.json
- src/library/js/integration/catroid.js
- yarn.lock
https://jira.catrob.at/browse/BLOCKS-247
Blockly is updated to the latest version. In this version events were changed and these events are fixed now in Catblocks.
> BLOCKS-247 Update Blockly and fix broken events

- src/library/css/share.css
- src/library/js/integration/share.js
Thumbnail of object is now shown next to it's title
https://jira.catrob.at/browse/BLOCKS-254
> BLOCKS-254 Thumbnails of objects and objects scenes shall be visible on share

- i18n/create_json.js
- test/jsunit/parser/parser.test.js
Remove wrong newlines through regex.
https://jira.catrob.at/browse/BLOCKS-273
> BLOCKS-273 Don't show newlines from formulars (unless the user typed it in)

- github_actions/catroid-support-checker-action/require/checker.py
Checks if a new language was added in Catroid before copying it in Catblocks
https://jira.catrob.at/browse/BLOCKS-280
> BLOCKS-280 Fix Checker.py in github_action/catroid-support-checker-action/

- src/library/js/integration/utils.js
https://jira.catrob.at/browse/BLOCKS-274
Information button fix in android
> BLOCKS-274 Information button is either not clickable or doesn't work

- github_actions/catroid-support-checker-action/action.yml
- github_actions/catroid-support-checker-action/entrypoint.sh
fix the push issue
https://jira.catrob.at/browse/BLOCKS-283
> BLOCKS-283 catroid-support-checker-action should push automatically

- src/common/js/parser/parser.js
- src/library/js/blocks/categories/test.js
- test/jsunit/parser/parser.test.js
https://jira.catrob.at/browse/BLOCKS-290
new EndBrick test case and fix Parameterized Brick second value in EndBrick
> BLOCKS-290 Catblocks Test which checks values in Endbrick

- .github/workflows/interval_catroid_check_action.yaml
- github_actions/catroid-support-checker-action/Dockerfile
- github_actions/catroid-support-checker-action/action.yml
- github_actions/catroid-support-checker-action/entrypoint.sh
- github_actions/catroid-support-checker-action/require/checker.py
https://jira.catrob.at/browse/BLOCKS-293
Create automatic pull request when Catroid language files are updated.
The PR is created by a POST Request.
> BLOCKS-293 Checker.py doesn't make a Pull request

- docker/po-review/Dockerfile
PO Review Container works again
> BLOCKS-296 Fix PO Review Container

- src/common/js/parser/parser.js
Fix issue in parser so it won't crash, once a reference is in xml file.
https://jira.catrob.at/browse/BLOCKS-294
> BLOCKS-294 Parameterized Brick crash

- github_actions/gh-pages-deploy-action/entrypoint.sh
> BLOCKS-299 fix broken gh pages action

- github_actions/gh-pages-deploy-action/entrypoint.sh
> BLOCKS-299 Fix commit message of GH Pages Action

- github_actions/gh-pages-deploy-action/entrypoint.sh
- package.json
- src/intern/html/ghpages.html
- src/intern/js/index.js
- src/intern/js/render/utils.js
https://jira.catrob.at/browse/BLOCKS-300
Fix GH-Pages testing page.
> BLOCKS-300 Fix github pages icons

- src/common/js/parser/parser.js
- src/intern/html/testing.html
- src/intern/js/index.js
- src/library/js/integration/brick_id_generator.js
- src/library/js/integration/catroid.js
- src/library/js/integration/utils.js
- src/library/js/lib_catroid.js
- test/jsunit/block/block.test.js
- test/programs/udb_nested_recursion.xml
https://jira.catrob.at/browse/BLOCKS-244
Every Block now gets a unique ID to access it in Android.
Thus, we get the ability for drag & drop, order checks and existence checks.
> BLOCKS-244 More Catblocks Tests in Android

- src/library/js/integration/catroid.js
> BLOCKS-289 Add help to Catblocks

- i18n/strings_to_json_mapping.json
- src/library/js/blocks/categories/sound.js
> BLOCKS-309 PlaySoundAtBrick missing in CatBlocks

- test/jsunit/share/share.test.js
https://jira.catrob.at/browse/BLOCKS-307
Checked for possible problems, none of them are existing anymore.
Fixed one bug which I discovered during those checks.
> BLOCKS-307 Serialization problem in tests possible
