Catrobat/Catblocks

src/js/parser/parser.js
test/jsunit/parser/parser.test.js

Fixed catroid to catblocks parser to support user variables. User variable name shows now up inside the dropdown field. User variable can be either inside the current brick or defined via a reference.

Blocks 43 - parsing user variable properly

---

src/css/style.css
src/html/render.html
src/js/render/file_dropper.js
src/js/render/message_box.js

Add ability to read file type from head of file. Ignore unsupported or unneeded files and continue with rendering. Display info message for unsupported files.
https://jira.catrob.at/browse/BLOCKS-72

BLOCKS-72 In browser rendering does not work properly

---

src/js/parser/parser.js
test/jsunit/parser/parser.test.js

BLOCKS-60 
the bug was current parser version did not assign the bricks as child which are enclosed between the RepeatBrick and LoopEndBrick
and added it to the end of the RepeatBrick instead of into the RepeatBrick
added a for-loop which iterates through the content of the RepeatBrick and add it to his loopOrIfBricklist

BLOCKS-60 Parser does not wrap properly RepeatBrick - LoopEndBrick combination

---

src/html/share.html
src/js/index.js

https://jira.catrob.at/browse/BLOCKS-115
share:dev is working now with new material-icons design.
Copied `<link>`, `<div>` and `<script>` tags from render.html. Moved javascript code from share.html to index.js.

BLOCKS-115 share is working again

---

src/js/parser/parser.js

Fixed the bug where some programs couldn't be rendered anymore in the share page
The problem was, that some ifBricks/IfElseBricks/RepeatBricks didn't fill their lists properly with bricks, so those programs couldn't be rendered anymore
I added this functionality now in the parser and the bricks get rendered properly again.

BLOCKS-80: some programs can't be rendered anymore

---

docker/po-review/README.md
docker/po-review/entrypoint.sh
src/js/index.js
webpack.config.js

https://jira.catrob.at/browse/BLOCKS-97
Changing display language in po-review docker is possible with environment variables now. When you set the environment variable with the -e flag on docker run, the display language of the blocks will be changed. If -e option is not set, then the default language is used. 
[See readme](https://github.com/georgsc/Catblocks/blob/BLOCKS-97/docker/po-review/README.md)

BLOCKS-97 set display language in po-review docker 

---

.gitignore
i18n/create_msg.js
package.json
release.config.js
src/html/release.html
src/js/catblocks_msgs.js
src/js/release.js
src/js/render/render.js
src/js/share/share.js

https://jira.catrob.at/browse/BLOCKS-119
Implemented webpack config `release.config.js`, which uses entrypoint `src/release.js`. It exports a CatBlocks-Object with functions `init` and `render`. Also removed some CSS classes, to not destroy the layout on Share.
To build the release use `yarn release`. The packaged Library is located in the release folder.

BLOCKS-119 implement release module and webpack config [MF]

---

.github/workflows/interval_brickcheck_action.yaml
brick-support-checker-action/Dockerfile
brick-support-checker-action/action.yml
brick-support-checker-action/entrypoint.sh
brick-support-checker-action/require/checker.py

A docker pulls the Catroid and Catblocks projects and compares the supported bricks using a python script. If there are unsupported bricks in Catblocks, a report is sent to Slack.
https://jira.catrob.at/browse/BLOCKS-84

BLOCKS-84 Support Unsupported Bricks [BP]

---

test/jsunit/share/share.test.js

In our auto tests we often used 
querySelector(..) !== undefined && querySelector(..).innerHTML 
which got changed to 
querySelector(..) !== null && querySelector(..).innerHTML 
because querying for "querySelector(..) !== undefined" was not really useful, so I changed all the querys which queryed for "querySelector(..) !== undefined" to "querySelector(..) !== null" and adjusted old tests, which got then wrong, because of this change.

BLOCKS-109: fixed tests - changed from "!= undefined" to "!= null"

---

src/js/index.js
test/jsunit/msg/msg.test.js

https://jira.catrob.at/browse/BLOCKS-124
changing language via PO-review docker is working again. Added current display language to config object in index.js Also added one new test to check if changing language on share is working.

BLOCKS-124 Setting display language is not working

---

i18n/strings_to_json_mapping.json
src/js/share/share.js
test/jsunit/msg/msg.test.js

https://jira.catrob.at/browse/BLOCKS-117
added translations for 'Scripts', 'Looks' and 'Sounds' and for each tab.
If there are no translations e.g. 'No Scripts found', I changed the translations for German to 'No Skripte found'.

BLOCKS-117 UI language translations are missing

---

i18n/create_msg.js
src/js/catblocks_msgs.js
src/js/index.js
test/jsunit/msg/msg.test.js

https://jira.catrob.at/browse/BLOCKS-118
If regional language suffix is unknown then the same language without the regional suffix is used. If this language is still unknown then the implementation uses the fallback language 'en'.
Created three tests to check if the current implementation works properly.

BLOCKS-118 Unknown regional language suffixes handled incorrectly

---

src/html/playground.html
src/js/parser/parser.js
src/js/playground/playground.js
src/js/render/render.js
src/js/share/share.js
src/js/share/utils.js
test/jsunit/parser/parser.test.js
test/jsunit/share/share.test.js
test/jsunit/share/share.utils.test.js

https://jira.catrob.at/browse/BLOCKS-111
Created new jsonDomToWorkspace function in utils to render blocks with json object.
So I deleted all unnecessary xml code in parser and fixed all tests. 
I changed the "from xml" function in playground to "from json" and also fixed "import using parser".

BLOCKS-111 Render SVG Blocks without XML

---

.github/workflows/merge_actions.yaml
.github/workflows/pull_request_actions.yml

A check ensures that actions are only executed on the GH Repository Catrobat/Catblocks. The problem is that on forked repositories they always fail.

BLOCKS-127 Add check for GH Actions

---

src/js/index.js

https://jira.catrob.at/browse/BLOCKS-120
added i18n folder attribute to share/render config. Catblocks Renderer should work again.

BLOCKS-120 Catblocks Renderer is not working

---

docker/po-review/README.md
src/intern/js/index.js
src/intern/js/render/utils.js
src/library/html/release.html
src/library/js/share/share.js
src/library/js/share/utils.js
test/jsunit/share/share.test.js
webpack.config.js

https://jira.catrob.at/browse/BLOCKS-91
All blocks can be displayed in RTL now. 
To test this implementation locally: set in index.js at line 14 `let isRtl = true;`. 
You can also test this implementation with po-review docker, please add  `-e DISPLAY_RTL=true` to the run command (see readme for more details).
There are still some issues left on this topic ([BLOCKS-92](https://jira.catrob.at/browse/BLOCKS-92) and [BLOCKS-93](https://jira.catrob.at/browse/BLOCKS-92)).

BLOCKS-91 Support right to left languages: bricks

---

src/library/js/share/share.js
test/jsunit/share/share.test.js

https://jira.catrob.at/browse/BLOCKS-92
Formulas are displayed in RTL too. 
To test this implementation locally: set in index.js at line 14 let isRtl = true;.
You can also test this implementation with po-review docker, please add -e DISPLAY_RTL=true to the run command (see readme for more details).

BLOCKS-92 Support right to left languages: formula

---

src/library/js/share/share.js

https://jira.catrob.at/browse/BLOCKS-93
share supports right to left layout. 
To test this implementation locally: set in index.js at line 14 let isRtl = true;.
You can also test this implementation with po-review docker, please add -e DISPLAY_RTL=true to the run command (see readme for more details).

BLOCKS-93 Support right to left languages: share layout

---

src/intern/html/render.html
src/intern/html/testing.html
src/library/css/share.css
src/library/html/release.html
src/library/js/share/share.js
test/jsunit/share/share.test.js

Added a magnifying glass button and an onclick() event on the image in share, to popup the image in a modal in the center of the screen.
Created a test in share.test.js for the popup, which should only open by clicking on the magnifying glass beside the image or by clicking on the image.

Blocks 89: Show larger version of look when the user taps on it in the list of looks, in a popup

---

src/intern/css/style.css
src/library/css/share.css

https://jira.catrob.at/browse/BLOCKS-144
disabled horizontal scrollbar in css.

BLOCKS-144 disable horizontal scrollbar [GS]

---

src/library/css/share.css
src/library/js/share/share.js
test/jsunit/share/share.test.js

https://jira.catrob.at/browse/BLOCKS-123
Removed our custom js function and added css class to handle chevron rotation. Now scene and card headers should have the same behavior as the card headers on [share](https://share.catrob.at/app/project/4a20f223-5cbf-11ea-a2ae-000c292a0f49).

BLOCKS-123 Expand More rotation should use CSS from Share

---

src/intern/html/playground.html
src/intern/js/index.js
src/intern/js/playground/playground.js
src/intern/js/render/utils.js
src/library/html/release.html
src/library/js/lib.js
src/library/js/share/share.js

https://jira.catrob.at/browse/BLOCKS-138
Removed the `setLocale()` function call without i18n folder as second parameter in index.js. Now Catblocks Renderer should work again. 
Also changing language on playground is working again.

BLOCKS-138 Catblocks Renderer is still not working

---

src/library/js/share/share.js
test/jsunit/share/share.test.js

https://jira.catrob.at/browse/BLOCKS-142
When the project has only one scene, then all objects are listed instead of the scene. 
Modified tests and added one new test.

BLOCKS-142 Do not show scene when the project has only one scene

---

.github/workflows/interval_catroid_check_action.yaml
catroid-support-checker-action/entrypoint.sh
catroid-support-checker-action/require/checker.py

https://jira.catrob.at/browse/BLOCKS-141
checker.py is working again. Now a slack message is also generated when there are no changes detected or when the script is failing. Script is now executed twice a week (on Mondays and on Thursdays at 7 am).

BLOCKS-141 catroid-support-checker-action is not working

---

src/intern/js/index.js
test/jsunit/performance/performance.test.js

https://jira.catrob.at/browse/BLOCKS-137
Created new test file with one performance test to measure rendering time of the default test program (The Binding of Krishna).

BLOCKS-137 Display rendering time when testing

---

src/library/js/share/utils.js
test/jsunit/block/block.test.js

Zebra was working, but not properly, because if it was dark at the end of one script, it started dark at the next, which shouldn't be anymore.

BLOCKS-145: fixed zebra bug, where color didn't reset properly

---

gh-pages-deploy-action/entrypoint.sh

https://jira.catrob.at/browse/BLOCKS-82
Actual Behavior: gh-pages-deploy-action/entrypoint.sh: line 14: =0: not found
Expected Behavior: Retrieve return value the right way or remove the usage of return value

BLOCKS-82 entrypoint.sh line 14 =0 not found

---

.github/workflows/merge_actions.yaml
gh-deploy-new-develop-on-webtest/Dockerfile
gh-deploy-new-develop-on-webtest/action.yml
gh-deploy-new-develop-on-webtest/entrypoint.sh

Created the docker file to automatically create a PR to the webtest develop server based on a branch at the webtest server which enables the PR for the develop branch and the branch we would use

BLOCKS-98: created automated gh-action for deploy to webtest develop branch

---

src/intern/js/render/utils.js

Support more image types on local rendering
Using the local upload implementation, the generateBase64 function only supports png, jpg and jpeg for now. Add at least gif, bmp and svg to the known types.
https://jira.catrob.at/browse/BLOCKS-110

BLOCKS-110 Support more image types on local rendering

---

src/intern/js/render/render.js
src/library/js/lib.js
src/library/js/share/share.js
test/jsunit/share/share.test.js

created a loading animation for the lazy loading of sceneobjects, now a loading modal gets popped when you click on a scene the first time

BLOCKS-155: created loading animation for lazy loading of sceneobjects

---

i18n/strings_to_json_mapping.json
src/library/js/blocks/categories/sound.js

added setinstrument brick for sounds

BLOCKS-162: added set instrument brick

---

src/intern/js/render/render.js

added visible seperation for renderer

BLOCKS-168: added seperation for render

---

src/intern/html/render.html
src/library/js/share/share.js

set now the style to max-width and max-height on the looks modal instead of height and with
and also cleaned up render.html file

BLOCKS-186: resolved the issue with blurred images to be original size

---

src/library/js/share/share.js

readjusted the color of the modals to be the same and now both modals have the translation on the close button

BLOCKS-171: adjusted both modals to look the same

---

src/common/js/parser/parser.js
test/jsunit/parser/parser.test.js

Change default value of brick inputs from "---" to empty string.
https://jira.catrob.at/browse/BLOCKS-189

BLOCKS-189 Empty strings displayed wrong

---

src/library/js/share/share.js
src/library/js/share/utils.js
test/jsunit/share/share.test.js

Lazy loading of images to save bandwidth (especially on mobile devices)
https://jira.catrob.at/browse/BLOCKS-195

BLOCKS-195 Load Images per Object, not per Scene

---

.vscode/launch.json
src/library/html/release.html
src/library/js/share/share.js
test/jsunit/performance/performance.test.js

https://jira.catrob.at/browse/BLOCKS-192
Opening multiple scenes fired multiple render events => fixed
The performance test didn't work anymore, because it only displayed the overview of the program => fixed

BLOCKS-192 Rendering way too slow on released Library

---

src/library/js/share/share.js

https://jira.catrob.at/browse/BLOCKS-194
If there are line breaks in a formula, they are displayed in the popup correctly now.

BLOCKS-194 Linebreaks in formula popup

---

src/intern/js/render/utils.js
src/library/html/release.html
src/library/js/share/share.js
src/library/js/share/utils.js
test/jsunit/share/share.test.js

https://jira.catrob.at/browse/BLOCKS-173
Added option to disable rendering scripts, sounds and images.

BLOCKS-173 Only blocks, not looks and not sounds

---

github_actions/catroid-support-checker-action/require/checker.py

UserDefinedBrick and UserDefinedReceiverBrick are already implemented - but in a different way. This means that they are not recognized by the support checker action so they have to be added to the ignored list.

BLOCKS-202 Add blocks to ignored list

---

src/common/js/parser/parser.js
src/library/js/share/share.js
test/jsunit/parser/parser.test.js
test/jsunit/share/share.test.js

https://jira.catrob.at/browse/BLOCKS-204
fixed lazy loading for single scene, instead loading scene name the program name is now loaded.

BLOCKS-204 Fix Lazy Loading

---

.vscode/launch.json
assets/scripts.svg
src/library/css/share.css
src/library/js/share/share.js
src/library/js/share/utils.js
test/jsunit/msg/msg.test.js

Android Team removed their i18n Strings for Scripts, Looks and Sounds Tabs. Switching to Icons.
https://jira.catrob.at/browse/BLOCKS-228

BLOCKS-228 Strings for Scripts, Looks and Sounds are undefined

---

src/common/js/parser/parser.js

Add brick id to parser to use the same id as Catroid.
https://jira.catrob.at/browse/BLOCKS-181

BLOCKS-181 Unify Catblocks and Catroid Brick IDs

---

i18n/catroid_strings/values-en/strings.xml
i18n/strings_to_json_mapping.json
src/common/js/parser/parser.js
src/library/js/share/share.js

Add a context menu entry in Catblocks to switch to selected 1D brick.
https://jira.catrob.at/browse/BLOCKS-182

BLOCKS-182 First entry on context menu of a brick opens the 1D view of the scripts at the same place

---

i18n/catroid_strings/values-en/strings.xml
i18n/strings_to_json_mapping.json
src/common/js/parser/parser.js
src/library/css/share.css
src/library/js/blocks/bricks.js
src/library/js/blocks/categories/dummy.js
src/library/js/blocks/categories/index.js
src/library/js/blocks/colours.js
src/library/js/share/share.js
src/library/js/share/utils.js
test/jsunit/block/block.test.js

Allows to drag & drop bricks in Catblocks.
The position of the moved bricks is saved - each group of bricks has an invisible dummy script brick as parent.
https://jira.catrob.at/browse/BLOCKS-223

BLOCKS-223 Allow moving bricks or brick blocks

---

src/common/js/parser/formula.js
test/jsunit/parser/parser.test.js

remove trailing zeros from bricks.
https://jira.catrob.at/browse/BLOCKS-207

BLOCKS-207 Do not show any trailing 0 after the dot in rational numbers

---

src/common/js/parser/parser.js
src/library/css/common.css
src/library/js/integration/utils.js

https://jira.catrob.at/browse/BLOCKS-232
Disabled bricks are displayed with reduced opacity from now on.

BLOCKS-232 Disabled bricks displayed wrong

---

src/common/js/parser/formula.js
test/jsunit/parser/parser.test.js

https://jira.catrob.at/browse/BLOCKS-237
Spaces at beginning and end are no longer be trimmed.

BLOCKS-237 Spaces at beginning and end of strings not shown

---

assets/scripts_icon.svg
src/library/html/release.html
src/library/js/integration/share.js
src/library/js/lib_share.js
test/jsunit/share/share.test.js

Include Catblocks.init media config parameter for icons

BLOCKS-275 Load image icons from correct path

---

github_actions/catroid-support-checker-action/action.yml
github_actions/catroid-support-checker-action/require/checker.py

Automatically fetch Language Updates from Catroid via Github Action
https://jira.catrob.at/browse/BLOCKS-250

BLOCKS-250 Automatically fetch Language Updates from Catroid

---

github_actions/catroid-support-checker-action/require/checker.py

checker.py checks now via github action if all necessary strings in strings.xml are in strings_to_json_mapping.json
https://jira.catrob.at/browse/BLOCKS-282

BLOCKS-282 Check automatically if all strings from string.xml are contained

---

github_actions/catroid-support-checker-action/require/checker.py

Fix the issue why checker.py fails to execute
https://jira.catrob.at/browse/BLOCKS-285

BLOCKS-285 Checker.py failed to execute

---

.vscode/launch.json
i18n/create_json.js

Fix the annoying message that an XML Tag is not supported

BLOCKS-MAINTENANCE fix skipping tag message and windows launch config

---

src/library/js/integration/catroid.js
src/library/js/lib_catroid.js

https://jira.catrob.at/browse/BLOCKS-227
Focus correct brick when switching between 1D and 2D views.

BLOCKS-227 Restore place/brick in View when switching between 1D & 2D

---

.eslintrc
package.json
src/common/js/parser/parser.js
src/intern/js/index.js
src/intern/js/playground/playground.js
src/library/js/catblocks_msgs.js
src/library/js/integration/catroid.js
src/library/js/integration/share.js
src/library/js/integration/utils.js
test/jsunit/msg/msg.test.js
yarn.lock

https://jira.catrob.at/browse/BLOCKS-297
Update Blockly and other npm packages. Fix language problems with new Blockly scoping --> we can't write arbitrary objects to Blockly anymore.

BLOCKS-297 Update Blockly

---

webpack.release.build.config.js
webpack.release.dev.config.js

https://jira.catrob.at/browse/BLOCKS-304
Minifying didn't work anymore, because we forgot to add this option when the webpack version got updated.

BLOCKS-304 Fix minifying of dev versions

---

i18n/strings_to_json_mapping.json
src/library/js/integration/utils.js

https://jira.catrob.at/browse/BLOCKS-291
Implemented changing of message0 to a plural version, when it is necessary. It is done in utils.js, as it is the only place in code, where it was possible. Respectively, a new string to JSON mapping has been added in order to be working in every language.

BLOCKS-291 Parameterized Brick message0 is wrong when multiple Lists are selected

---

github_actions/gh-deploy-new-develop-on-webtest/entrypoint.sh
github_actions/gh-pages-deploy-action/entrypoint.sh

https://jira.catrob.at/browse/BLOCKS-303
Fix two GH merge actions:
- The action that creates a PR to Catroweb on merge to master.
- The action that merges the changes to gh-pages no merge to develop.

BLOCKS-303 GH merge actions fail

---

src/library/js/integration/catroid.js

For creating unit tests for "add bricks", it's necessary that some HTML elements have an ID. (Categories and Bricks)

BLOCKS-318 Add ID to HTML elements for adding bricks

---

src/library/js/integration/utils.js
test/jsunit/share/share.test.js

https://jira.catrob.at/browse/BLOCKS-212
Eventhandler didn't work accordingly, if the DOM element which fired the event was a subnode.

BLOCKS-212 Looks are not shown as thumbnails, only after tapping on the magnifying glass
